spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml
